apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  name: wiki-js-ingress
  namespace: troop-46
spec:
  tls:
    - hosts:
        - bsa46.com
      secretName: troop-46-tls
  rules:
    - host: bsa46.com
      http:
        paths:
          - backend:
              service:
                name: drupal-service
                port:
                  number: 80
            pathType: Prefix
            path: /
